### ISSUE TITLE
error when running ‘node crawler' command

### ISSUE THREAD

**Issue by aglaiawong** [ruffrey/google-finance-crawler#1]
Hi! I'm new to Node.js. When I run your project with 'node crawler', it shows the following. May I understand how to resolve the issue please? I'm running on Windows with windows node.js installed. I followed the command line in Readme uptil 'node crawler'. Thanks.

```
$ node crawler
module.js:549
    throw err;
    ^

Error: Cannot find module 'crawler'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Spring 2018\fyp\google-finance-crawler\crawler.js:
13:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by ruffrey** [comment]
This project is pretty out of date, it probably needs various package upgrades. I took a look for a few mins and the `crawler` npm package won't build on newer versions of Node.

**Comment by ruffrey** [comment]
I pushed a new version which will require Node.js v10. However, this script is highly dependent on the HTML layout of google finance, which has changed over the years. Someone would need to spend an hour or so changing the `stockParser.js` file to look at the right HTML tags or classes.

**Comment by aglaiawong** [comment]
OK. Thank you! I would try to adjust based on that. Thanks!
